apiVersion: v1
kind: List
items:
- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    labels:
      component.opendatahub.io/name: jupyterhub
      opendatahub.io/component: 'true'
      opendatahub.io/notebook-image: 'true'
    annotations:
      opendatahub.io/notebook-image-url: "https://github.com/thoth-station/s2i-minimal-notebook"
      opendatahub.io/notebook-image-name: "CUDA"
      opendatahub.io/notebook-image-desc: "Jupyter notebook image with GPU support and minimal dependency set to start experimenting with Jupyter environment."
    name: "minimal-gpu"
  spec:
    lookupPolicy:
      local: true
    tags:
    - annotations:
        opendatahub.io/notebook-software: '[{"name":"Python","version":"v3.8.3"},{"name":"CUDA","version":"11.0.3"}]'
        opendatahub.io/notebook-python-dependencies: '[{"name":"JupyterLab","version":"3.0.14"},{"name":"Notebook","version":"6.3.0"}]'
      name: "py3.8-cuda-11.0.3"
      referencePolicy:
        type: Local
- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    labels:
      component.opendatahub.io/name: jupyterhub
      opendatahub.io/component: 'true'
      opendatahub.io/notebook-image: 'true'
    annotations:
      opendatahub.io/notebook-image-url: "https://github.com/thoth-station/s2i-tensorflow-gpu-notebook"
      opendatahub.io/notebook-image-name: "TensorFlow"
      opendatahub.io/notebook-image-desc: "Jupyter notebook image with GPU support and includes TensorFlow libraries and dependencies to start experimenting with advanced AI/ML notebooks."
    name: "tensorflow-gpu"
  spec:
    lookupPolicy:
      local: true
    tags:
    - annotations:
        opendatahub.io/notebook-software: '[{"name":"Python","version":"v3.8.3"},{"name":"TensorFlow","version":"==2.4.1"},{"name":"CUDA","version":"11.0.3"}]'
        opendatahub.io/notebook-python-dependencies: '[{"name":"TensorFlow","version":"==2.4.1"},{"name":"Tensorboard","version":"2.4.1"},{"name":"Boto3","version":"1.17.11"},{"name":"Kafka-Python","version":"2.0.2"},{"name":"Matplotlib","version":"3.1.3"},{"name":"Numpy","version":"1.19.5"},{"name":"Pandas","version":"0.25.3"},{"name":"Scipy","version":"1.6.2"}]'
      name: "py3.8-cuda-11.0.3"
      referencePolicy:
        type: Local
- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    labels:
      component.opendatahub.io/name: jupyterhub
      opendatahub.io/component: 'true'
      opendatahub.io/notebook-image: 'true'
    annotations:
      opendatahub.io/notebook-image-url: "https://github.com/thoth-station/s2i-pytorch-notebook"
      opendatahub.io/notebook-image-name: "PyTorch"
      opendatahub.io/notebook-image-desc: "Jupyter notebook image with GPU support and includes PyTorch libraries and dependencies to start experimenting with advanced AI/ML notebooks."
    name: "pytorch-gpu"
  spec:
    lookupPolicy:
      local: true
    tags:
    - annotations:
        opendatahub.io/notebook-software: '[{"name":"Python","version":"v3.8.3"},{"name":"PyTorch","version":"==1.8.1"},{"name":"CUDA","version":"11.0.3"}]'
        opendatahub.io/notebook-python-dependencies: '[{"name":"PyTorch","version":"==1.8.1"},{"name":"Tensorboard","version":"1.15.0"},{"name":"Boto3","version":"1.17.11"},{"name":"Kafka-Python","version":"2.0.2"},{"name":"Matplotlib","version":"3.4.1"},{"name":"Numpy","version":"1.20.2"},{"name":"Pandas","version":"1.2.3"},{"name":"Scipy","version":"1.6.2"}]'
      name: "py3.8-cuda-11.0.3"
      referencePolicy:
        type: Local
- kind: BuildConfig
  apiVersion: build.openshift.io/v1
  metadata:
    name: s2i-minimal-gpu-cuda-$(cuda_version)-notebook
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: 'minimal-gpu:py3.8-cuda-$(cuda_version)'
    strategy:
      type: Docker
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: '$(cuda_version)-cuda-s2i-thoth-ubi8-py38:latest'
        noCache: true
        dockerfilePath: Dockerfile
    source:
      type: Git
      git:
        ref: python38
        uri: 'https://github.com/thoth-station/s2i-minimal-notebook'
    triggers:
      - type: ConfigChange
      - type: ImageChange
    resources:
      limits:
        memory: 16Gi
      requests:
        memory: 16Gi
- kind: BuildConfig
  apiVersion: build.openshift.io/v1
  metadata:
    name: s2i-tensorflow-gpu-cuda-$(cuda_version)-notebook
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: 'tensorflow-gpu:py3.8-cuda-$(cuda_version)'
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: 'minimal-gpu:py3.8-cuda-$(cuda_version)'
    source:
      type: Git
      git:
        ref: python38
        uri: 'https://github.com/thoth-station/s2i-tensorflow-gpu-notebook'
    triggers:
      - type: ConfigChange
      - type: ImageChange
    resources:
      limits:
        memory: 16Gi
      requests:
        memory: 6Gi
- kind: BuildConfig
  apiVersion: build.openshift.io/v1
  metadata:
    name: s2i-pytorch-gpu-cuda-$(cuda_version)-notebook
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: 'pytorch-gpu:py3.8-cuda-$(cuda_version)'
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: 'minimal-gpu:py3.8-cuda-$(cuda_version)'
    source:
      type: Git
      git:
        ref: python38
        uri: 'https://github.com/thoth-station/s2i-pytorch-notebook'
    triggers:
      - type: ConfigChange
      - type: ImageChange
    resources:
      limits:
        memory: 16Gi
      requests:
        memory: 6Gi
